// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBattle = `-- name: CreateBattle :one
INSERT INTO battles (creator_id, mode, genre, name, sample_pack_id, duration_minutes, max_participants)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, creator_id, name, mode, genre, sample_pack_id, status, duration_minutes, max_participants, current_listening_index, listening_order, started_at, completed_at, created_at
`

type CreateBattleParams struct {
	CreatorID       pgtype.UUID `json:"creator_id"`
	Mode            string      `json:"mode"`
	Genre           pgtype.Text `json:"genre"`
	Name            pgtype.Text `json:"name"`
	SamplePackID    pgtype.UUID `json:"sample_pack_id"`
	DurationMinutes int32       `json:"duration_minutes"`
	MaxParticipants int32       `json:"max_participants"`
}

func (q *Queries) CreateBattle(ctx context.Context, arg CreateBattleParams) (Battle, error) {
	row := q.db.QueryRow(ctx, createBattle,
		arg.CreatorID,
		arg.Mode,
		arg.Genre,
		arg.Name,
		arg.SamplePackID,
		arg.DurationMinutes,
		arg.MaxParticipants,
	)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Mode,
		&i.Genre,
		&i.SamplePackID,
		&i.Status,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.CurrentListeningIndex,
		&i.ListeningOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBattle = `-- name: DeleteBattle :exec
DELETE FROM battles WHERE id = $1
`

func (q *Queries) DeleteBattle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBattle, id)
	return err
}

const deleteBattleParticipants = `-- name: DeleteBattleParticipants :exec
DELETE FROM battle_participants WHERE battle_id = $1
`

func (q *Queries) DeleteBattleParticipants(ctx context.Context, battleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBattleParticipants, battleID)
	return err
}

const getBattle = `-- name: GetBattle :one
SELECT id, creator_id, name, mode, genre, sample_pack_id, status, duration_minutes, max_participants, current_listening_index, listening_order, started_at, completed_at, created_at FROM battles
WHERE id = $1
`

func (q *Queries) GetBattle(ctx context.Context, id pgtype.UUID) (Battle, error) {
	row := q.db.QueryRow(ctx, getBattle, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Mode,
		&i.Genre,
		&i.SamplePackID,
		&i.Status,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.CurrentListeningIndex,
		&i.ListeningOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBattles = `-- name: ListBattles :many
SELECT id, creator_id, name, mode, genre, sample_pack_id, status, duration_minutes, max_participants, current_listening_index, listening_order, started_at, completed_at, created_at FROM battles
WHERE status = 'waiting'
ORDER BY created_at DESC
`

func (q *Queries) ListBattles(ctx context.Context) ([]Battle, error) {
	rows, err := q.db.Query(ctx, listBattles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Battle
	for rows.Next() {
		var i Battle
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Mode,
			&i.Genre,
			&i.SamplePackID,
			&i.Status,
			&i.DurationMinutes,
			&i.MaxParticipants,
			&i.CurrentListeningIndex,
			&i.ListeningOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startBattle = `-- name: StartBattle :one
UPDATE battles
SET status = 'in_progress', started_at = NOW()
WHERE id = $1
RETURNING id, creator_id, name, mode, genre, sample_pack_id, status, duration_minutes, max_participants, current_listening_index, listening_order, started_at, completed_at, created_at
`

func (q *Queries) StartBattle(ctx context.Context, id pgtype.UUID) (Battle, error) {
	row := q.db.QueryRow(ctx, startBattle, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Mode,
		&i.Genre,
		&i.SamplePackID,
		&i.Status,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.CurrentListeningIndex,
		&i.ListeningOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateBattleStatus = `-- name: UpdateBattleStatus :one
UPDATE battles
SET status = $2
WHERE id = $1
RETURNING id, creator_id, name, mode, genre, sample_pack_id, status, duration_minutes, max_participants, current_listening_index, listening_order, started_at, completed_at, created_at
`

type UpdateBattleStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateBattleStatus(ctx context.Context, arg UpdateBattleStatusParams) (Battle, error) {
	row := q.db.QueryRow(ctx, updateBattleStatus, arg.ID, arg.Status)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Mode,
		&i.Genre,
		&i.SamplePackID,
		&i.Status,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.CurrentListeningIndex,
		&i.ListeningOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateListeningIndex = `-- name: UpdateListeningIndex :one
UPDATE battles
SET current_listening_index = $2
WHERE id = $1
RETURNING id, creator_id, name, mode, genre, sample_pack_id, status, duration_minutes, max_participants, current_listening_index, listening_order, started_at, completed_at, created_at
`

type UpdateListeningIndexParams struct {
	ID                    pgtype.UUID `json:"id"`
	CurrentListeningIndex int32       `json:"current_listening_index"`
}

func (q *Queries) UpdateListeningIndex(ctx context.Context, arg UpdateListeningIndexParams) (Battle, error) {
	row := q.db.QueryRow(ctx, updateListeningIndex, arg.ID, arg.CurrentListeningIndex)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Mode,
		&i.Genre,
		&i.SamplePackID,
		&i.Status,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.CurrentListeningIndex,
		&i.ListeningOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateListeningOrder = `-- name: UpdateListeningOrder :one
UPDATE battles
SET listening_order = $2
WHERE id = $1
RETURNING id, creator_id, name, mode, genre, sample_pack_id, status, duration_minutes, max_participants, current_listening_index, listening_order, started_at, completed_at, created_at
`

type UpdateListeningOrderParams struct {
	ID             pgtype.UUID   `json:"id"`
	ListeningOrder []pgtype.UUID `json:"listening_order"`
}

func (q *Queries) UpdateListeningOrder(ctx context.Context, arg UpdateListeningOrderParams) (Battle, error) {
	row := q.db.QueryRow(ctx, updateListeningOrder, arg.ID, arg.ListeningOrder)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Mode,
		&i.Genre,
		&i.SamplePackID,
		&i.Status,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.CurrentListeningIndex,
		&i.ListeningOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
