// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBattle = `-- name: CreateBattle :one
INSERT INTO battles (creator_id, mode, genre, sample_pack_id, duration_minutes, max_participants)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, creator_id, mode, genre, sample_pack_id, status, duration_minutes, max_participants, started_at, completed_at, created_at
`

type CreateBattleParams struct {
	CreatorID       pgtype.UUID `json:"creator_id"`
	Mode            string      `json:"mode"`
	Genre           pgtype.Text `json:"genre"`
	SamplePackID    pgtype.UUID `json:"sample_pack_id"`
	DurationMinutes int32       `json:"duration_minutes"`
	MaxParticipants int32       `json:"max_participants"`
}

func (q *Queries) CreateBattle(ctx context.Context, arg CreateBattleParams) (Battle, error) {
	row := q.db.QueryRow(ctx, createBattle,
		arg.CreatorID,
		arg.Mode,
		arg.Genre,
		arg.SamplePackID,
		arg.DurationMinutes,
		arg.MaxParticipants,
	)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Mode,
		&i.Genre,
		&i.SamplePackID,
		&i.Status,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBattle = `-- name: GetBattle :one
SELECT id, creator_id, mode, genre, sample_pack_id, status, duration_minutes, max_participants, started_at, completed_at, created_at FROM battles
WHERE id = $1
`

func (q *Queries) GetBattle(ctx context.Context, id pgtype.UUID) (Battle, error) {
	row := q.db.QueryRow(ctx, getBattle, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Mode,
		&i.Genre,
		&i.SamplePackID,
		&i.Status,
		&i.DurationMinutes,
		&i.MaxParticipants,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBattles = `-- name: ListBattles :many
SELECT id, creator_id, mode, genre, sample_pack_id, status, duration_minutes, max_participants, started_at, completed_at, created_at FROM battles
ORDER BY created_at DESC
`

func (q *Queries) ListBattles(ctx context.Context) ([]Battle, error) {
	rows, err := q.db.Query(ctx, listBattles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Battle
	for rows.Next() {
		var i Battle
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Mode,
			&i.Genre,
			&i.SamplePackID,
			&i.Status,
			&i.DurationMinutes,
			&i.MaxParticipants,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
