// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle_participants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allFinishedEarly = `-- name: AllFinishedEarly :one
SELECT COUNT(*) = COUNT(*) FILTER (WHERE finished_early = TRUE)
FROM battle_participants
WHERE battle_id = $1
`

func (q *Queries) AllFinishedEarly(ctx context.Context, battleID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, allFinishedEarly, battleID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const confirmVotes = `-- name: ConfirmVotes :one
UPDATE battle_participants
SET votes_confirmed = TRUE
WHERE id = $1
RETURNING id, battle_id, user_id, beat_url, joined_at, duration_seconds, submitted_at, votes_confirmed, finished_early, created_at
`

func (q *Queries) ConfirmVotes(ctx context.Context, id pgtype.UUID) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, confirmVotes, id)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.DurationSeconds,
		&i.SubmittedAt,
		&i.VotesConfirmed,
		&i.FinishedEarly,
		&i.CreatedAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO battle_participants (battle_id, user_id)
VALUES ($1, $2)
RETURNING id, battle_id, user_id, beat_url, joined_at, duration_seconds, submitted_at, votes_confirmed, finished_early, created_at
`

type CreateParticipantParams struct {
	BattleID pgtype.UUID `json:"battle_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, createParticipant, arg.BattleID, arg.UserID)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.DurationSeconds,
		&i.SubmittedAt,
		&i.VotesConfirmed,
		&i.FinishedEarly,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, battle_id, user_id, beat_url, joined_at, duration_seconds, submitted_at, votes_confirmed, finished_early, created_at FROM battle_participants
WHERE battle_id = $1 AND user_id = $2
`

type GetParticipantParams struct {
	BattleID pgtype.UUID `json:"battle_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.BattleID, arg.UserID)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.DurationSeconds,
		&i.SubmittedAt,
		&i.VotesConfirmed,
		&i.FinishedEarly,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT id, battle_id, user_id, beat_url, joined_at, duration_seconds, submitted_at, votes_confirmed, finished_early, created_at FROM battle_participants
WHERE id = $1
`

func (q *Queries) GetParticipantByID(ctx context.Context, id pgtype.UUID) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipantByID, id)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.DurationSeconds,
		&i.SubmittedAt,
		&i.VotesConfirmed,
		&i.FinishedEarly,
		&i.CreatedAt,
	)
	return i, err
}

const listParticipants = `-- name: ListParticipants :many
SELECT
    bp.id,
    bp.battle_id,
    bp.user_id,
    bp.beat_url,
    bp.submitted_at,
    bp.votes_confirmed,
    bp.duration_seconds,
    bp.finished_early,
    bp.created_at AS created_at,
    u.display_name,
    u.username,
    u.elo_rating,
    u.battles_played,
    u.battles_won,
    u.profile_picture_url
FROM battle_participants bp
JOIN users u ON bp.user_id = u.id
WHERE bp.battle_id = $1
ORDER BY bp.created_at ASC
`

type ListParticipantsRow struct {
	ID                pgtype.UUID        `json:"id"`
	BattleID          pgtype.UUID        `json:"battle_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	BeatUrl           pgtype.Text        `json:"beat_url"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	VotesConfirmed    bool               `json:"votes_confirmed"`
	DurationSeconds   pgtype.Int4        `json:"duration_seconds"`
	FinishedEarly     bool               `json:"finished_early"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DisplayName       string             `json:"display_name"`
	Username          string             `json:"username"`
	EloRating         int32              `json:"elo_rating"`
	BattlesPlayed     int32              `json:"battles_played"`
	BattlesWon        int32              `json:"battles_won"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
}

func (q *Queries) ListParticipants(ctx context.Context, battleID pgtype.UUID) ([]ListParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listParticipants, battleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsRow
	for rows.Next() {
		var i ListParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.BattleID,
			&i.UserID,
			&i.BeatUrl,
			&i.SubmittedAt,
			&i.VotesConfirmed,
			&i.DurationSeconds,
			&i.FinishedEarly,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Username,
			&i.EloRating,
			&i.BattlesPlayed,
			&i.BattlesWon,
			&i.ProfilePictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFinishedEarly = `-- name: MarkFinishedEarly :exec
UPDATE battle_participants
SET finished_early = TRUE
WHERE battle_id = $1 AND user_id = $2
`

type MarkFinishedEarlyParams struct {
	BattleID pgtype.UUID `json:"battle_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkFinishedEarly(ctx context.Context, arg MarkFinishedEarlyParams) error {
	_, err := q.db.Exec(ctx, markFinishedEarly, arg.BattleID, arg.UserID)
	return err
}

const removeParticipant = `-- name: RemoveParticipant :exec
DELETE FROM battle_participants
WHERE battle_id = $1 AND user_id = $2
`

type RemoveParticipantParams struct {
	BattleID pgtype.UUID `json:"battle_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.BattleID, arg.UserID)
	return err
}

const unconfirmVotes = `-- name: UnconfirmVotes :one
UPDATE battle_participants
SET votes_confirmed = false
WHERE battle_id = $1 AND user_id = $2
RETURNING id, battle_id, user_id, beat_url, joined_at, duration_seconds, submitted_at, votes_confirmed, finished_early, created_at
`

type UnconfirmVotesParams struct {
	BattleID pgtype.UUID `json:"battle_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UnconfirmVotes(ctx context.Context, arg UnconfirmVotesParams) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, unconfirmVotes, arg.BattleID, arg.UserID)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.DurationSeconds,
		&i.SubmittedAt,
		&i.VotesConfirmed,
		&i.FinishedEarly,
		&i.CreatedAt,
	)
	return i, err
}

const updateParticipantBeatURL = `-- name: UpdateParticipantBeatURL :one
UPDATE battle_participants
SET beat_url = $2, submitted_at = $3
WHERE id = $1
RETURNING id, battle_id, user_id, beat_url, joined_at, duration_seconds, submitted_at, votes_confirmed, finished_early, created_at
`

type UpdateParticipantBeatURLParams struct {
	ID          pgtype.UUID        `json:"id"`
	BeatUrl     pgtype.Text        `json:"beat_url"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) UpdateParticipantBeatURL(ctx context.Context, arg UpdateParticipantBeatURLParams) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantBeatURL, arg.ID, arg.BeatUrl, arg.SubmittedAt)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.DurationSeconds,
		&i.SubmittedAt,
		&i.VotesConfirmed,
		&i.FinishedEarly,
		&i.CreatedAt,
	)
	return i, err
}

const updateParticipantDuration = `-- name: UpdateParticipantDuration :one
UPDATE battle_participants
SET duration_seconds = $2
WHERE id = $1
RETURNING id, battle_id, user_id, beat_url, joined_at, duration_seconds, submitted_at, votes_confirmed, finished_early, created_at
`

type UpdateParticipantDurationParams struct {
	ID              pgtype.UUID `json:"id"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
}

func (q *Queries) UpdateParticipantDuration(ctx context.Context, arg UpdateParticipantDurationParams) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantDuration, arg.ID, arg.DurationSeconds)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.DurationSeconds,
		&i.SubmittedAt,
		&i.VotesConfirmed,
		&i.FinishedEarly,
		&i.CreatedAt,
	)
	return i, err
}
