// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteQueueTicketsByIDs = `-- name: DeleteQueueTicketsByIDs :exec
DELETE FROM battle_queue
WHERE id = ($1::uuid[])
`

func (q *Queries) DeleteQueueTicketsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQueueTicketsByIDs, dollar_1)
	return err
}

const dequeueUser = `-- name: DequeueUser :exec
DELETE FROM battle_queue
WHERE user_id = $1
`

func (q *Queries) DequeueUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, dequeueUser, userID)
	return err
}

const enqueueUser = `-- name: EnqueueUser :one
INSERT INTO battle_queue (user_id, genres)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
RETURNING id, user_id, genres, joined_at
`

type EnqueueUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Genres []string    `json:"genres"`
}

func (q *Queries) EnqueueUser(ctx context.Context, arg EnqueueUserParams) (BattleQueue, error) {
	row := q.db.QueryRow(ctx, enqueueUser, arg.UserID, arg.Genres)
	var i BattleQueue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Genres,
		&i.JoinedAt,
	)
	return i, err
}

const getQueueTicket = `-- name: GetQueueTicket :one
SELECT id, user_id, genres, joined_at FROM battle_queue
WHERE user_id = $1
`

func (q *Queries) GetQueueTicket(ctx context.Context, userID pgtype.UUID) (BattleQueue, error) {
	row := q.db.QueryRow(ctx, getQueueTicket, userID)
	var i BattleQueue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Genres,
		&i.JoinedAt,
	)
	return i, err
}

const listQueueTickets = `-- name: ListQueueTickets :many
SELECT id, user_id, genres, joined_at FROM battle_queue
ORDER BY joined_at ASC
`

func (q *Queries) ListQueueTickets(ctx context.Context) ([]BattleQueue, error) {
	rows, err := q.db.Query(ctx, listQueueTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BattleQueue
	for rows.Next() {
		var i BattleQueue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Genres,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
