// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle_participants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmVotes = `-- name: ConfirmVotes :one
UPDATE battle_participants
SET votes_confirmed = TRUE
WHERE id = $1
RETURNING id, battle_id, user_id, beat_url, joined_at, submitted_at, votes_confirmed
`

func (q *Queries) ConfirmVotes(ctx context.Context, id pgtype.UUID) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, confirmVotes, id)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.SubmittedAt,
		&i.VotesConfirmed,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO battle_participants (battle_id, user_id)
VALUES ($1, $2)
RETURNING id, battle_id, user_id, beat_url, joined_at, submitted_at, votes_confirmed
`

type CreateParticipantParams struct {
	BattleID pgtype.UUID `json:"battle_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, createParticipant, arg.BattleID, arg.UserID)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.SubmittedAt,
		&i.VotesConfirmed,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, battle_id, user_id, beat_url, joined_at, submitted_at, votes_confirmed FROM battle_participants
WHERE battle_id = $1 AND user_id = $2
`

type GetParticipantParams struct {
	BattleID pgtype.UUID `json:"battle_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.BattleID, arg.UserID)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.SubmittedAt,
		&i.VotesConfirmed,
	)
	return i, err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT id, battle_id, user_id, beat_url, joined_at, submitted_at, votes_confirmed FROM battle_participants
WHERE id = $1
`

func (q *Queries) GetParticipantByID(ctx context.Context, id pgtype.UUID) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipantByID, id)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.SubmittedAt,
		&i.VotesConfirmed,
	)
	return i, err
}

const listParticipants = `-- name: ListParticipants :many
SELECT id, battle_id, user_id, beat_url, joined_at, submitted_at, votes_confirmed FROM battle_participants
WHERE battle_id = $1 ORDER BY joined_at
`

func (q *Queries) ListParticipants(ctx context.Context, battleID pgtype.UUID) ([]BattleParticipant, error) {
	rows, err := q.db.Query(ctx, listParticipants, battleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BattleParticipant
	for rows.Next() {
		var i BattleParticipant
		if err := rows.Scan(
			&i.ID,
			&i.BattleID,
			&i.UserID,
			&i.BeatUrl,
			&i.JoinedAt,
			&i.SubmittedAt,
			&i.VotesConfirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParticipantBeatURL = `-- name: UpdateParticipantBeatURL :one
UPDATE battle_participants
SET beat_url = $2, submitted_at = $3
WHERE id = $1
RETURNING id, battle_id, user_id, beat_url, joined_at, submitted_at, votes_confirmed
`

type UpdateParticipantBeatURLParams struct {
	ID          pgtype.UUID        `json:"id"`
	BeatUrl     pgtype.Text        `json:"beat_url"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) UpdateParticipantBeatURL(ctx context.Context, arg UpdateParticipantBeatURLParams) (BattleParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantBeatURL, arg.ID, arg.BeatUrl, arg.SubmittedAt)
	var i BattleParticipant
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.UserID,
		&i.BeatUrl,
		&i.JoinedAt,
		&i.SubmittedAt,
		&i.VotesConfirmed,
	)
	return i, err
}
