// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Battle struct {
	ID                    pgtype.UUID        `json:"id"`
	CreatorID             pgtype.UUID        `json:"creator_id"`
	Name                  pgtype.Text        `json:"name"`
	Mode                  string             `json:"mode"`
	Genre                 pgtype.Text        `json:"genre"`
	SamplePackID          pgtype.UUID        `json:"sample_pack_id"`
	Status                string             `json:"status"`
	DurationMinutes       int32              `json:"duration_minutes"`
	MaxParticipants       int32              `json:"max_participants"`
	CurrentListeningIndex int32              `json:"current_listening_index"`
	ListeningOrder        []pgtype.UUID      `json:"listening_order"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type BattleParticipant struct {
	ID                pgtype.UUID        `json:"id"`
	BattleID          pgtype.UUID        `json:"battle_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	BeatUrl           pgtype.Text        `json:"beat_url"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
	DurationSeconds   pgtype.Int4        `json:"duration_seconds"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	VotesConfirmed    bool               `json:"votes_confirmed"`
	ParticipantStatus string             `json:"participant_status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type BattleQueue struct {
	ID       pgtype.UUID        `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Genres   []string           `json:"genres"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type SamplePack struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Genres    []string           `json:"genres"`
	FileUrl   string             `json:"file_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Username          string             `json:"username"`
	DisplayName       string             `json:"display_name"`
	EloRating         int32              `json:"elo_rating"`
	BattlesPlayed     int32              `json:"battles_played"`
	BattlesWon        int32              `json:"battles_won"`
	ClerkID           pgtype.Text        `json:"clerk_id"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Vote struct {
	ID                    pgtype.UUID        `json:"id"`
	BattleID              pgtype.UUID        `json:"battle_id"`
	VoterID               pgtype.UUID        `json:"voter_id"`
	VotedForParticipantID pgtype.UUID        `json:"voted_for_participant_id"`
	Score                 int32              `json:"score"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}
