// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sample_packs.sql

package db

import (
	"context"
)

const createSamplePack = `-- name: CreateSamplePack :one
INSERT INTO sample_packs (name, genres, file_url)
VALUES ($1, $2, $3)
RETURNING id, name, genres, file_url, created_at
`

type CreateSamplePackParams struct {
	Name    string   `json:"name"`
	Genres  []string `json:"genres"`
	FileUrl string   `json:"file_url"`
}

func (q *Queries) CreateSamplePack(ctx context.Context, arg CreateSamplePackParams) (SamplePack, error) {
	row := q.db.QueryRow(ctx, createSamplePack, arg.Name, arg.Genres, arg.FileUrl)
	var i SamplePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genres,
		&i.FileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getRandomPackByGenre = `-- name: GetRandomPackByGenre :one
SELECT id, name, genres, file_url, created_at FROM sample_packs
WHERE $1 = ANY(genres)
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomPackByGenre(ctx context.Context, genres []string) (SamplePack, error) {
	row := q.db.QueryRow(ctx, getRandomPackByGenre, genres)
	var i SamplePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genres,
		&i.FileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listSamplePacks = `-- name: ListSamplePacks :many
SELECT id, name, genres, file_url, created_at FROM sample_packs ORDER BY created_at DESC
`

func (q *Queries) ListSamplePacks(ctx context.Context) ([]SamplePack, error) {
	rows, err := q.db.Query(ctx, listSamplePacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamplePack
	for rows.Next() {
		var i SamplePack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Genres,
			&i.FileUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
