// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name)
VALUES ($1, $2)
RETURNING id, username, display_name, elo_rating, battles_played, battles_won, clerk_id, created_at, updated_at
`

type CreateUserParams struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EloRating,
		&i.BattlesPlayed,
		&i.BattlesWon,
		&i.ClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, username, display_name, elo_rating, battles_played, battles_won, clerk_id, created_at, updated_at FROM users
WHERE clerk_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EloRating,
		&i.BattlesPlayed,
		&i.BattlesWon,
		&i.ClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, elo_rating, battles_played, battles_won, clerk_id, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EloRating,
		&i.BattlesPlayed,
		&i.BattlesWon,
		&i.ClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementBattlesPlayed = `-- name: IncrementBattlesPlayed :one
UPDATE users
SET battles_played = battles_played + 1
WHERE id = $1
RETURNING id, username, display_name, elo_rating, battles_played, battles_won, clerk_id, created_at, updated_at
`

func (q *Queries) IncrementBattlesPlayed(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, incrementBattlesPlayed, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EloRating,
		&i.BattlesPlayed,
		&i.BattlesWon,
		&i.ClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementBattlesWon = `-- name: IncrementBattlesWon :one
UPDATE users
SET battles_won = battles_won + 1
WHERE id = $1
RETURNING id, username, display_name, elo_rating, battles_played, battles_won, clerk_id, created_at, updated_at
`

func (q *Queries) IncrementBattlesWon(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, incrementBattlesWon, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EloRating,
		&i.BattlesPlayed,
		&i.BattlesWon,
		&i.ClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserElo = `-- name: UpdateUserElo :one
UPDATE users
SET elo_rating = $2
WHERE id = $1
RETURNING id, username, display_name, elo_rating, battles_played, battles_won, clerk_id, created_at, updated_at
`

type UpdateUserEloParams struct {
	ID        pgtype.UUID `json:"id"`
	EloRating int32       `json:"elo_rating"`
}

func (q *Queries) UpdateUserElo(ctx context.Context, arg UpdateUserEloParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserElo, arg.ID, arg.EloRating)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EloRating,
		&i.BattlesPlayed,
		&i.BattlesWon,
		&i.ClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByClerkID = `-- name: UpsertUserByClerkID :one
INSERT INTO users (username, display_name, clerk_id)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_id) DO UPDATE
SET clerk_id = EXCLUDED.clerk_id
RETURNING id, username, display_name, elo_rating, battles_played, battles_won, clerk_id, created_at, updated_at
`

type UpsertUserByClerkIDParams struct {
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
	ClerkID     pgtype.Text `json:"clerk_id"`
}

func (q *Queries) UpsertUserByClerkID(ctx context.Context, arg UpsertUserByClerkIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByClerkID, arg.Username, arg.DisplayName, arg.ClerkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.EloRating,
		&i.BattlesPlayed,
		&i.BattlesWon,
		&i.ClerkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
