// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVote = `-- name: CreateVote :one
INSERT INTO votes (battle_id, voter_id, voted_for_participant_id, score)
VALUES ($1, $2, $3, $4)
RETURNING id, battle_id, voter_id, voted_for_participant_id, score, created_at
`

type CreateVoteParams struct {
	BattleID              pgtype.UUID `json:"battle_id"`
	VoterID               pgtype.UUID `json:"voter_id"`
	VotedForParticipantID pgtype.UUID `json:"voted_for_participant_id"`
	Score                 int32       `json:"score"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote,
		arg.BattleID,
		arg.VoterID,
		arg.VotedForParticipantID,
		arg.Score,
	)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.VoterID,
		&i.VotedForParticipantID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteByVoterAndParticipant = `-- name: GetVoteByVoterAndParticipant :one
SELECT id, battle_id, voter_id, voted_for_participant_id, score, created_at FROM votes
WHERE battle_id = $1 AND voter_id = $2 AND voted_for_participant_id = $3
`

type GetVoteByVoterAndParticipantParams struct {
	BattleID              pgtype.UUID `json:"battle_id"`
	VoterID               pgtype.UUID `json:"voter_id"`
	VotedForParticipantID pgtype.UUID `json:"voted_for_participant_id"`
}

func (q *Queries) GetVoteByVoterAndParticipant(ctx context.Context, arg GetVoteByVoterAndParticipantParams) (Vote, error) {
	row := q.db.QueryRow(ctx, getVoteByVoterAndParticipant, arg.BattleID, arg.VoterID, arg.VotedForParticipantID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.BattleID,
		&i.VoterID,
		&i.VotedForParticipantID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const getVotesForBattle = `-- name: GetVotesForBattle :many
SELECT id, battle_id, voter_id, voted_for_participant_id, score, created_at FROM votes
WHERE battle_id = $1
`

func (q *Queries) GetVotesForBattle(ctx context.Context, battleID pgtype.UUID) ([]Vote, error) {
	rows, err := q.db.Query(ctx, getVotesForBattle, battleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.BattleID,
			&i.VoterID,
			&i.VotedForParticipantID,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
